Repository MondevCodes/lacoste, pull requests merged in 2025-07, with the labels that each got.

#14 Update presences
  src/lib/constants/forms.ts
  src/lib/constants/schemas.ts
  src/modules/core/commands/send.ts
  src/modules/core/interactions/updatePresences.ts
  src/modules/form/interactions/acompanhamento.ts
  src/modules/form/interactions/acompanhamentoAdm.ts
  tsconfig.json
Labels: enhancement

#15 Extended permissions update presences
  src/modules/core/commands/send.ts
  src/modules/core/interactions/updatePresences.ts
Labels: enhancement

#16 Fix the permission role
  src/modules/core/interactions/updatePresences.ts
Labels: bug

#17 link_slash_command
  src/modules/core/commands/link.ts
  src/modules/work/interactions/department.ts
Labels: enhancement

#18 Change time form presence
  src/modules/core/commands/link.ts
  src/modules/form/interactions/organizacional.ts
Labels: enhancement

#19 New verification for last presence
  src/modules/core/commands/verify.ts
Labels: enhancement

#22 Verify change embed time and organizacional dates
  package.json
  src/lib/utilities/discord.ts
  src/modules/core/commands/pingDiscord.ts
  src/modules/core/commands/verify.ts
  src/modules/form/interactions/organizacional.ts
Labels: enhancement

#23 Don't link bots
  src/lib/utilities/discord.ts
  src/modules/core/commands/link.ts
Labels: enhancement

#24 Fix shouldPromote
  src/modules/core/commands/verify.ts
Labels: bug, enhancement
